### ISSUE TITLE
Add action output for matches

### ISSUE THREAD

**Issue by stackptr** [freckle/grep-action#13]
An output that specifies how many matches were found would make the action useful for scenarios outside of feedback in pull requests. For example, the number of occurrences of a pattern could be tracked as a kind of code quality metric:

```yaml
on:
  pull_request:
  push:
    branches: main

jobs:
  grep:
    runs-on: ubuntu-latest
    steps:
      - id: grep
        uses: freckle/grep-action@v1
        with:
          only-changed: ${{ github.ref == 'refs/heads/main' && false || true }}
          patterns: |
            - pattern: "(TODO|FIXME)"
              syntax: extended
              paths:
                - "**/*"
              level: warning
              title: "TODO found"
      - uses: company/report-metric
        with:
          metric-name: todo-or-fixme-comments
          metric-value: ${{ steps.grep.outputs.total-matches }}
```

While the above supposes the existence of an output like `total-matches`, a more flexible output could be accomplished by extending the input `patterns.pattern` with an `id`, like:

```yaml
on:
  pull_request:
  push:
    branches: main

jobs:
  grep:
    runs-on: ubuntu-latest
    steps:
      - id: grep
        uses: freckle/grep-action@v1
        with:
          only-changed: ${{ github.ref == 'refs/heads/main' && false || true }}
          patterns: |
            - pattern: "TODO"
              paths:
                - "**/*"
              level: warning
              title: "TODO found"
            - id: fixme
              pattern: "FIXME"
              paths:
                - "**/*"
              level: warning
              title: "FIXME found"
      - name: Log FIXME metric 
        run: |
          matches=${{ steps.grep.output.matches }}
          req_json=$(echo "$matches" | jq '{name: "todo-comments", value: .fixme.count}')
          
          curl --fail-with-body -X POST "https://api.example.com/metrics" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${DATADOG_API_KEY}" \
            -d "$req_json"
```
